export const TOGGLE_HEADER = 'TOGGLE_HEADER';
export const START_SPINNER = 'START_SPINNER';
export const STOP_SPINNER = 'STOP_SPINNER';
export const START_SUCCESS = 'START_SUCCESS';
export const START_FAIL = 'START_FAIL';
export const START_TIMEOUT = 'START_TIMEOUT';
export const START_SESSION = 'START_SESSION';